services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=greenbook
      - MYSQL_USER=greenbook
      - MYSQL_PASSWORD=greenbook123
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/greenbook
      - SPRING_DATASOURCE_USERNAME=greenbook
      - SPRING_DATASOURCE_PASSWORD=greenbook123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - GOOGLE_API_KEY=

